FROM alpine:3.16.1

VOLUME /sys/fs/cgroup

RUN apk update \
    && apk add openrc \
    && sed -i '/tty/d' /etc/inittab \
    && sed -i 's/mount -t tmpfs/# mount -t tmpfs/g' /lib/rc/sh/init.sh \
    && sed -i 's/hostname \$opts/# hostname \$opts/g' /etc/init.d/hostname \
    && echo 'rc_provide="loopback net"' >> /etc/rc.conf \
    && sed -i 's/cgroup_add_service /# cgroup_add_service /g' /lib/rc/sh/openrc-run.sh \
    && sed -i 's/^#\(rc_logger="YES"\)\$/\1/' /etc/rc.conf \
    && sed -i 's/#rc_sys=""/rc_sys="lxc"/g' /etc/rc.conf \
    && rm -rf /var/cache/apk/*
    
CMD ["/sbin/init"]